### ISSUE TITLE
Mann test results

### ISSUE THREAD

**Issue by brat-eek** [tristandeleu/ntm-one-shot#10]
Does the implementation match the results as on the paper at test time ? Atleast are the accuracies even close because I dont seem to be even getting close. Thanks in adv.

**Comment by tristandeleu** [comment]
I did manage to get similar results for the 5 classes/episode experiment. Here are the results I got a few months back
![image](https://cloud.githubusercontent.com/assets/2018752/24803501/bdba4470-1bab-11e7-9b5a-c1f98671a6c3.png)

**Comment by brat-eek** [comment]
Thanks for the assurance! I might have screwed up while playing with it. :+1:

**Comment by hspark84** [comment]
Why is the 1st instance high in the early episodes ?
In the paper, that was low and flat in the early episodes.

**Comment by tristandeleu** [comment]
I can't explain the behavior of the 1st instance unfortunately. When I saw that first I thought I did something wrong with the way I'm computing the metrics, but as it gets closer to the results of the paper with a larger number of episodes, I think it's just a matter of (un)lucky initialization.

**Comment by HyoungWooPark** [comment]
Is the above results from training MANN with 5classes/episode experiment? 
I would get the same results from omniglot dataset by an instruction which you wrote.
In your implementation, I cannot find how I can get the test results from trained MANN.
How can I test it after training?
