### ISSUE TITLE
should I use GPU to train it?

### ISSUE THREAD

**Issue by BoyuanJiang** [tristandeleu/ntm-one-shot#12]
If other specifications of computer are same(like cpu,ram),train it use GPU will faster than no GPU?If so,how many times faster?

**Comment by tristandeleu** [comment]
I can't say for sure about this model in particular, but I didn't get any significant speedup with a GPU on a vanilla NTM.
If you end up using a GPU, please share your experience (if training was any faster).

**Comment by BoyuanJiang** [comment]
I tried to use gpu but even slower than cpu.
