### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mnestis** [tristandeleu/ntm-one-shot#19]
Thanks for taking the time to write this code. It's particularly valuable, seeing as the authors of the original paper chose not to release their version. At time of writing, 89 forks and 367 stars. 

Nevertheless, it'd be a lot easier to reuse if it had an explicit license attached.

Thanks,
Darren..

**Comment by tristandeleu** [comment]
Hi Darren, somehow I missed that when I created the project. I added a Licence file (MIT Licence).
Thank you for the notice!
