### ISSUE TITLE
Warning: Downsampling error has been moved to theano.tensor.signal.pool module

### ISSUE THREAD

**Issue by PawarKishori** [tristandeleu/ntm-one-shot#7]
Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 90.0% of memory, cuDNN Mixed dnn version. The header is from one ver│···············
sion, but we link with a different version (5005, 5110))                                                                                         │···············
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.s│···············
ignal.pool module.                                                                                                                               │···············
  "downsample module has been moved to the theano.tensor.signal.pool module.")

**Comment by Exception4U** [comment]
Same error .. please comment

**Comment by Davidzhang95** [comment]
Hi ,can you execute this program（ignore the warning）? i met two errors in my issue,could you offer me some help? thank you so much.😭

by the way, upgrate theano to 0.9.0,lasagne to 2.0.0dev might work,because i have met this problem,now it disappeared although i don't know exactly what happened.

**Comment by Exception4U** [comment]
sure what are errors u got ?

**Comment by tristandeleu** [comment]
This downsample module was called by Lasagne 0.1.0 but is now deprecated in Theano. As suggested above, the solution is to install the 0.2.0dev1 version of Lasagne, along with the version 0.9.0 of Theano.
I added a `requirements.txt` to the project. I updated the [`README`](https://github.com/tristandeleu/ntm-one-shot/blob/master/README.md) with instructions to get started. Thanks for reporting that issue!

**Comment by DavidZhang88** [comment]
@Exception4U Thank you,Windows error 267 and ValueError: sample larger than population ,have you got them before?

**Comment by PawarKishori** [comment]
@DavidZhang88, @tristandeleu Thanks for the solution. Now I am free from the warning which I was getting earlier. But can you tell me how much time your code took for executing 1Million episodes?

**Comment by tristandeleu** [comment]
I haven't tried on a machine with a GPU, but when I tested it on CPU it took 24h for 30k episodes.

**Comment by Exception4U** [comment]
@DavidZhang88 I did not encounter this error but sample error is because of wrong signature of math.random function . are you sure you are using the proper numpy version with theano ? Did you install theano using pip if yes then it should take care of that

**Comment by DavidZhang88** [comment]
@Exception4U,my problem has been solved,Thank you for your help😉.
